### ISSUE TITLE
Polkadot color system 

### ISSUE THREAD

**Issue by behzad888** [polkadot-js/apps#433]
I think button primary color in the Polkadot theme isn't clear and I think that button on bellow is disabled. so, I have a suggestion as material colors based on #430 

![check](https://user-images.githubusercontent.com/9346614/48286478-02917e80-e47b-11e8-99e4-6396455dff39.jpg)

**Comment by jacogr** [comment]
cc @Tbaut

**Comment by behzad888** [comment]
This is my suggestion!

```css
/* apps/SideBar.css */
.apps--SideBar {
  background: #364150;
  ...	

/* ui-app/app.css */
#root {
  color: #364150;
  ...

/* ui-app/_colors-polkadot.css */
$green: #29B4B6;
$orange: #f36a5a;
$red: #e7505a;
$pewter-blue: #4B77BE;
$dark-sky-blue: #578EBE;
$silver-chalice: #acb7ca;
$cadet-grey: #708096;
$light-slate-gray: #b4bcc8;

/* ui-app/components.css */
.ui--output {
  background: #f5f8fd
  ...

/* ui-app/components.css */
.ui--output.error {
  background-color: #fef7f8;
  border-color: #f0868e;
  ...

/* ui-app/components.css */
.ui--InputFile {
  ...
  &.error {
    background-color: #fef7f8;
    border-color: #f0868e;
  }

/* app-transfer/index.css */
.error {
  background-color: #fef7f8;
  border-color: #e7505a;
  color: #e7505a;
}

/* app-transfer/index.css */
.warning {
  background-color: #faeaa9;
  border-color: #f3cc31;
}

/* ui-app/app.css */
h1 {
  color: #666;
  ...

/* ui-app/app.css */
.ui.action.input:not([class*="left action"])>input:focus {
    border-right-color: #3598dc!important;
}

/* ui-app/semantic.css */
.ui.button:disabled, .ui.buttons .disabled.button, .ui.disabled.active.button, .ui.disabled.button, .ui.disabled.button:hover{
  opacity: 0.4!important;
}
```
